[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.simple"

[deploy]
startCommand = "dotnet ConstructionTracker.Web.Host.dll"
healthcheckPath = "/swagger"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
ASPNETCORE_ENVIRONMENT = "Production"
ASPNETCORE_URLS = "http://0.0.0.0:${PORT}"
ConnectionStrings__Default = "${DATABASE_URL}"
App__ServerRootAddress = "https://${RAILWAY_PUBLIC_DOMAIN}/"
App__ClientRootAddress = "https://${RAILWAY_PUBLIC_DOMAIN}/"
